### ISSUE TITLE
insmod: ERROR: could not insert module: Unknown symbol in module

### ISSUE THREAD

**Issue by whidrasl** [src-d/coreos-nvidia#3]
Hi! I'm using CoreOS 1632.2.1 and can't insert kernel module with such error:

`core@localhost ~ $ cat /etc/os-release`
`NAME="Container Linux by CoreOS"`
`ID=coreos`
`VERSION=1632.2.1`
`VERSION_ID=1632.2.1`
`BUILD_ID=2018-02-01-2053`
`PRETTY_NAME="Container Linux by CoreOS 1632.2.1 (Ladybug)"`
`ANSI_COLOR="38;5;75"`
`HOME_URL="https://coreos.com/"`
`BUG_REPORT_URL="https://issues.coreos.com"`
`COREOS_BOARD="amd64-usr"`
`core@localhost ~ $ docker run --rm -it --privileged --volume /:/rootfs/ srcd/coreos-nvidia:1632.2.1`
`insmod: ERROR: could not insert module /opt/nvidia/lib/modules/4.14.16/video/nvidia.ko: Unknown symbol in module`

**Comment by sr-ix** [comment]
Experiencing the same issue, same version on an AWS instance.

**Comment by lsjostro** [comment]
Apparently there is new deps in the latest release.. if you load ipmi_devintf first it will work

modprobe ipmi_devintf

**Comment by abwaqas** [comment]
/usr/lib/modules/3.10.0-957.27.2.el7.x86_64/weak-updates/drbd84/drbd.ko in centos7 COREOS insmod error: unknown symbol in module

**Comment by smola** [comment]
@abwaqas Please, could you open a new issue? Please, include:
- Operating system and version (e.g. `cat /etc/os-release`)
- The exact command you ran.
- Full log
